using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace emiteat.NexUI.Editor.IDGenerator
{
    /// <summary>
    /// Emits strongly-typed constant classes (UIScreenIds, UIStateKeys, UIActionKeys,
    /// UIMotionIds, UIThemeIds, UIElementIds) from registries and manual key lists. Designed
    /// so a future DesignerMetadataAsset can be added as another source without changing
    /// the output shape.
    /// </summary>
    public static class NexUIIDGenerator
    {
        public static void Generate(NexUIIDGeneratorSettings settings)
        {
            if (settings == null)
            {
                Debug.LogError("[NexUI] ID generator: settings is null.");
                return;
            }

            Directory.CreateDirectory(settings.outputFolder);

            WriteClass(settings, "UIScreenIds", CollectScreenIds(settings));
            WriteClass(settings, "UIStateKeys", ToPairs(settings.stateKeys));
            WriteClass(settings, "UIActionKeys", ToPairs(settings.actionKeys));
            WriteClass(settings, "UIElementIds", ToPairs(settings.elementIds));
            WriteClass(settings, "UIMotionIds", CollectMotionIds(settings));
            WriteClass(settings, "UIThemeIds", CollectThemeIds(settings));

            AssetDatabase.Refresh();
            Debug.Log($"[NexUI] ID generation complete ??{settings.outputFolder}");
        }

        private static IEnumerable<KeyValuePair<string, string>> CollectScreenIds(NexUIIDGeneratorSettings s)
        {
            var list = new List<KeyValuePair<string, string>>();
            if (s.screenRegistry?.screens != null)
                foreach (var def in s.screenRegistry.screens)
                    if (def != null && !string.IsNullOrEmpty(def.identity.screenId))
                        list.Add(new KeyValuePair<string, string>(def.identity.screenId, def.identity.screenId));
            return list;
        }

        private static IEnumerable<KeyValuePair<string, string>> CollectMotionIds(NexUIIDGeneratorSettings s)
        {
            var list = new List<KeyValuePair<string, string>>();
            if (s.motionRegistry?.motions != null)
                foreach (var m in s.motionRegistry.motions)
                    if (m != null && !string.IsNullOrEmpty(m.motionId))
                        list.Add(new KeyValuePair<string, string>(m.motionId, m.motionId));
            return list;
        }

        private static IEnumerable<KeyValuePair<string, string>> CollectThemeIds(NexUIIDGeneratorSettings s)
        {
            var list = new List<KeyValuePair<string, string>>();
            if (s.themeRegistry?.themes != null)
                foreach (var t in s.themeRegistry.themes)
                    if (t != null && !string.IsNullOrEmpty(t.themeId))
                        list.Add(new KeyValuePair<string, string>(t.themeId, t.themeId));
            return list;
        }

        private static IEnumerable<KeyValuePair<string, string>> ToPairs(string[] values)
        {
            var list = new List<KeyValuePair<string, string>>();
            if (values != null)
                foreach (var v in values)
                    if (!string.IsNullOrEmpty(v))
                        list.Add(new KeyValuePair<string, string>(v, v));
            return list;
        }

        private static void WriteClass(NexUIIDGeneratorSettings settings, string className,
            IEnumerable<KeyValuePair<string, string>> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> NexUI ID Generator. Do not edit by hand. </auto-generated>");
            sb.AppendLine($"namespace {settings.codeNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            var used = new HashSet<string>();
            foreach (var pair in entries)
            {
                var name = ToIdentifier(pair.Key);
                while (!used.Add(name)) name += "_";
                sb.AppendLine($"        public const string {name} = \"{Escape(pair.Value)}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(settings.outputFolder, className + ".cs"), sb.ToString());
        }

        private static string ToIdentifier(string raw)
        {
            var sb = new StringBuilder();
            bool capitalizeNext = true;
            foreach (var c in raw)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                    capitalizeNext = false;
                }
                else
                {
                    capitalizeNext = true;
                }
            }
            var id = sb.ToString();
            if (id.Length == 0) id = "_";
            if (char.IsDigit(id[0])) id = "_" + id;
            return id;
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
